### PR TITLE
Federation to Stitching SDL

### PR DESCRIPTION
**Pull request by gmac**
This refactors the federation example to convert a Federation SDL into a Stitching SDL, at which time it can be plugged directly into a stitched schema. Unfortunately, we've still got an outstanding bug with the reliability of `__typename`. Demonstration:

```
yarn start-services

# new tab
yarn start-gateway
```

Go to http://localhost:4000/graphql and query for the following:

```graphql
query {
  user(id: "1") {
    username
    reviews {
      body
      author {
        id
        username
      }
      product {
        upc
        name
        acceptsNewReviews
      }
    }
  }
}
```

If you look at the console output, you can see the request flow. The initial request sequence works fine. Users requests Reviews and gets a response. The response from the Reviews service looks like this:

```json
[
  {
    "reviews": [
      {
        "body": "Love it!",
        "author": {
          "id": "1"
        },
        "product": {
          "upc": "1"
        },
        "id": "1"
      },
      {
        "body": "Too expensive.",
        "author": {
          "id": "1"
        },
        "product": {
          "upc": "2"
        },
        "id": "2"
      }
    ],
    "id": "1",
    "__typename": "User"
  }
]
```

HOWEVER – notice that the `author` and `product` objects on each review do not include a `__typename`. This is accurate to what Stitching requested from the service. The problem is, those objects spawn key requests to subsequent services, at which time the request keys look like this:

```js
variables: {
  _v0_representations: [
    { id: '1', __typename: undefined },
    { id: '1', __typename: undefined }
  ]
}
```

So, there are two general approaches here, I think:

1. Stitching needs to be way more strict about requesting `__typename` from every single object, which seems heavy-handed.
2. A simpler solution might just be to manually build `__typename` into the key, the way the [current federation example does it](https://github.com/gmac/schema-stitching-handbook/blob/master/federation-services/lib/fetch_federation_subschema.js#L26-L32). Given that we know the type that merge config is being built for, it shouldn't be too big a lift to build the associated typename into the key function.

cc @yaacovCR.

### CODE REVIEW

**Comment by yaacovCR** [comment]
I think we do option 2 already https://github.com/ardatan/graphql-tools/blob/master/packages/stitch/src/stitchingInfo.ts#L52

**Comment by yaacovCR** [comment]
Aha. The bug is that as "an optimization" we don't at all request the key for a nested object from a service when the request includes only fields that are part of the key. I have to think more deeply as to why I thought this "optimization" was a good idea and if it only breaks for the type name or just more generally....

**Comment by yaacovCR** [comment]
Meaning it might be possible to keep that optimization for every part of key except typename...

**Comment by gmac** [comment]
Hmm, not sure I follow that. Running the example, I see the user and
product sub-objects requested from the subservice even though they only
contain key fields, so they were definitely queried. It sounds like what
you’re saying is that they shouldn’t be queried at all with this
optimization?

To the point of the optimization itself, that’d be super useful if it did
omit key-only requests for user and product (though again, I don’t see it
doing that). The reason that’s valuable is that most resolvers start by
querying for a record and then pick fields off of it, so it’s sad if you
end up making extra queries for fields you already have. Would be awesome
if that optimization worked reliably.

**Comment by yaacovCR** [comment]
That optimization is a bit different. It requests the key fields for nested
objects but if there are multiple fields within a key, and the request only
actually includes a portion of the key fields and no other fields, it won't
request the remainder of the key fields, presumably because you have them
already if you were able to get to that service altogether.

An example would probably help, and may also help us figure out if this
should ever be optimized in this way. Not too much time these days on my
end, it would perhaps be best maybe to remove this optimization and add it
back in when we can prove reliability more formally.

**Comment by yaacovCR** [comment]
A simpler example of this optimization at work is if the key consists only of a single ID field, let's say, and the request also contains only the single ID field, there is no need to add the ID field to the request, it's only if other fields are requested do we need to add the ID field.....

**Comment by yaacovCR** [comment]
https://github.com/ardatan/graphql-tools/blob/e28c6a2b13cbf7a0c1b52aaa8aafc8ec428d89d6/packages/delegate/src/mergeFields.ts#L81-83

**Comment by gmac** [comment]
Why does the key ever need to be added when the request includes the key? (Regardless of other fields being present).

either way, from what you’re describing, I’m not really hearing anything that sounds like a tangible optimization; this sounds mostly like field de-duplication, which (aside from being an eyesore to human onlookers) doesn’t have a practical impact on machine execution.

**Comment by yaacovCR** [comment]
Well I think with complex keys it can reduce requests, not just deduplicate, but either way I will have to dig deeper to understand this case better, thanks for raising it.

**Comment by yaacovCR** [comment]
tests passing with interfaces elsewhere... not sure i can surface the exact difference. are you able to reproduce the static SDL of the failing test, maybe?

i thought more about the optimization issue, and it shouldn't be an issue as the request is enriched with the extra selection sets prior to the fields being split up by schema, so the presence of additional fields should still make __typename be added.

it looks like in your schema, requests are not being enriched with selection sets at all...for reasons unknown...

**Comment by gmac** [comment]
> it looks like in your schema, requests are not being enriched with selection sets at all...for reasons unknown...

Did you upgrade to the latest stitching-directives package? That was fixed for me by the abstract types update.

**Comment by yaacovCR** [comment]
should be fixed in `@graphql-tools/stitch@7.1.7`

had nothing to do with above optimization, was only affecting computed fields, tracked it to isolation code, simple fix was to whitelist __typename when filtering

**Comment by gmac** [comment]
Wahoo!!!!

**Comment by gmac** [comment]
Thanks @yaacovCR! That did the trick. Works beautifully. Going to turn that SDL transformer into a NPM package and link it into this example that way!

**Pull request merged**
