### PR TITLE
Merging multiple keys formats

### PR DESCRIPTION
**Pull request by gmac**
@yaacovCR – I'm trying an experiment here using multiple key formats... should this work?

- Catalog service: `Product @key(selectionSet: "{ upc }") ... @merge(keyField: "upc")`
- Ecommerce service: `Product @key(selectionSet: "{ id upc }") ... @merge`
- Reviews service: `Product @key(selectionSet: "{ id }") ... @merge(keyField: "id")`

The theory here is that we should be able to traverse `Catalog > Ecomm > Reviews`, or `Reviews > Ecomm > Catalog`, or `Catalog < Ecomm > Reviews` as long as the intermediary service (ecommerce) uses an object key that accepts either key format. In practice, it seems that only going through the center (Ecomm) works. Starting at either edge results in the initial selection being made with no additional delegation attempts.

Sample query:

```graphql
query {
  # catalog service
  productsByUpc(upcs: ["1"]) {
    upc
    name
    retailPrice
    reviews {
      id
      body
    }
  }
  # ecommerce service
  productsByKey(keys: [
    { upc: "1" },
    { id: "102" }
  ]) {
    id
    upc
    name
    retailPrice
    reviews {
      id
      body
    }
  }
  # reviews service
  productsById(ids: ["101"]) {
    id
    name
    retailPrice
    reviews {
      id
      body
    }
  }
}
```

### CODE REVIEW

**Comment by gmac** [comment]
Poking around, it looks like querying for either of the outer edges (Catalog / Reviews) literally halts the process after the initial request is made. Is this a situation where the outer edges see the opposing key as an unproxyable field, and therefore give up? Is there a different way to do this kind of linkage?

**Comment by gmac** [comment]
Looks like linkage missing in the fields mapping. `id` resolves as an unproxyable field node for the schema keyed by UPC. Will have to take a closer look, but definitely reproducible:

```ts
import { graphql } from 'graphql';
import { makeExecutableSchema } from '@graphql-tools/schema';
import { stitchSchemas } from '../src/stitchSchemas';

describe('merge on multiple keys', () => {
  const catalogSchema = makeExecutableSchema({
    typeDefs: `
      type Product {
        upc: ID!
        name: String
      }

      type Query {
        productsByUpc(upcs: [ID!]!): [Product]!
      }
    `,
    resolvers: {
      Query: {
        productsByUpc: () => [{ upc: '1', name: 'Table' }],
      }
    }
  });

  const vendorSchema = makeExecutableSchema({
    typeDefs: `
      type Product {
        id: ID!
        upc: ID!
        price: Int
      }

      input ProductKey {
        id: ID
        upc: ID
      }

      type Query {
        productsByKey(keys: [ProductKey!]!): [Product]!
      }
    `,
    resolvers: {
      Query: {
        productsByKey: () => [{ id: '101', upc: '1', price: 879 }],
      }
    }
  });

  const reviewsSchema = makeExecutableSchema({
    typeDefs: `
      type Product {
        id: ID!
        reviews: [String]
      }

      type Query {
        productsById(ids: [ID!]!): [Product]!
      }
    `,
    resolvers: {
      Query: {
        productsById: () => [{ id: '101', reviews: ['works!'] }],
      }
    }
  });

  const gatewaySchema = stitchSchemas({
    subschemas: [
      {
        schema: catalogSchema,
        merge: {
          Product: {
            selectionSet: '{ upc }',
            fieldName: 'productsByUpc',
            key: ({ upc }) => upc,
            argsFromKeys: (upcs) => ({ upcs }),
          }
        }
      },
      {
        schema: vendorSchema,
        merge: {
          Product: {
            selectionSet: '{ upc id }',
            fieldName: 'productsByKey',
            key: ({ upc, id }) => ({ upc, id }),
            argsFromKeys: (keys) => ({ keys }),
          }
        }
      },
      {
        schema: reviewsSchema,
        merge: {
          Product: {
            selectionSet: '{ id }',
            fieldName: 'productsById',
            key: ({ id }) => id,
            argsFromKeys: (ids) => ({ ids }),
          }
        }
      }
    ]
  });

  const result = [{
    id: '101',
    upc: '1',
    name: 'Table',
    price: 879,
    reviews: ['works!'],
  }];

  test('works from middle join outward', async () => {
    const { data } = await graphql(gatewaySchema, `
      query {
        productsByKey(keys: [{ id: "101" }]) {
          id
          upc
          name
          price
          reviews
        }
      }
    `);

    expect(data.productsByKey).toEqual(result);
  });

  test('works from upc -> join -> id', async () => {
    const { data } = await graphql(gatewaySchema, `
      query {
        productsByUpc(upcs: ["1"]) {
          # id
          upc
          name
          price
          reviews
        }
      }
    `);

    expect(data.productsByUpc).toEqual(result);
  });

  test('works from id -> join -> upc', async () => {
    const { data } = await graphql(gatewaySchema, `
      query {
        productsById(ids: ["101"]) {
          id
          # upc
          name
          price
          reviews
        }
      }
    `);

    expect(data.productsByUpc).toEqual(result);
  });
});
```

**Comment by yaacovCR** [comment]
Should work!

**Comment by gmac** [comment]
I've opened a ticket for this here with my suspicions of the problem... https://github.com/ardatan/graphql-tools/issues/2515. I think `{ id upc }` cannot be fulfilled when each of the other services require `{ id }` and `{ upc }` respectively. I'm kind of thinking this would require types to support multiple merged type configurations where only `id` OR `upc` is required by the intermediary at a time.

**Comment by yaacovCR** [comment]
Hmmm. Gave it another think and I am not sure that this should work. The vendorSchema his declaring that it requires both ID and UPC to resolve records, not either one. Basically I am coming to the same conclusion I believe you already have. This is working as designed now, but there could possibly be a feature request to allow even more merging patterns.

**Pull request merged**
