### PR TITLE
Grooming descriptions & public fields

### PR DESCRIPTION
**Pull request by gmac**
One last planned topic on bringing order from chaos while trying to document a stitched schema, and serve a whitelisted version of its fields to the public.

### CODE REVIEW

**Comment by yaacovCR** [comment]
Hmmm. Looks like lack of type and field ownership get kind of messy in terms of documentation. If there is a strict requirement that everything be documented, wouldn't it be safer or plainer for documentation to be accurate in every sub schema so that it wouldn't matter which was pulled? And that if there was no such requirement, documentation would just be skipped?

Not that this isn't great wizardry...

**Comment by gmac** [comment]
@yaacovCR – managing descriptions is a foolishly hard problem for something that seems like it shouldn't be difficult. The problem is that you will _never_ update a description in all locations, or keep it updated. Then, someone adds important details in one location and they are not picked up because the description actually came from somewhere else. Leaving fields blank isn't really viable, because someone may add a crappy description to a undocumented field in an obscure corner, and that overrides a good description elsewhere.

This is the system we've adopted at Vox and it works really nicely for traffic control... There's always an annotation, and it's either The Official description, or a reference to where the official description is managed. We no longer have a team of 20+ people making ad-hoc changes all over the place and having nothing make it reliably into the schema.

**Comment by gmac** [comment]
Open to improvements here – https://github.com/gmac/schema-stitching-handbook/tree/master/curating-descriptions-and-fields#selecting-element-descriptions. However, this really is more of a human problem to solve than a technical one. This is a problem that really needs to be taken through the lens of many teams working in isolation where we expect frequent elbows in the ribs.

**Comment by yaacovCR** [comment]
It's just funny that we have abstracted away type ownership for everything except documentation, seems like some sort of deeper smell, but maybe not, anyway, maybe the documentation should exist separately on the gateway somehow?

**Comment by gmac** [comment]
Would be a neat problem to brainstorm on. To my knowledge, no one has
solved this very well – federation had all the same problems as I recall,
and they were doing the extremely primitive approach that stitching did by
default with last-service-wins. As a strategy that is terrible, because a
lot of times you end up with your most important descriptions managed in
your most obscure corners of the service architecture.

**Comment by gmac** [comment]
and compounding on that ^^, attempting to reorder services to prioritize descriptions is fraught with risk of messing up existing description selection order. I can't emphasize enough how big of a deal that `mergedTypeOptions` addition was once there was some reliable mechanism (...however imperfect...) to select descriptions regardless of service order.

**Pull request merged**
